### ISSUE TITLE
How to get TEXT (wet) instead of HTML (WARC)?

### ISSUE THREAD

**Issue by TheDailySpank** [michaelharms/comcrawl#30]
From what I understand, the index offsets are different for WET vs WARC. So is there a way to search for the WET files using index.commoncrawl.org or would we need to download all the indexes and re-write this script to read from there instead of querying index.commoncrawl.org?

**Comment by TheDailySpank** [comment]
Never mind. Looks like there is no index of the WET files commonly available so the entire list of WET files would need to be downloaded. Others have suggested attempting to use the offsets from the WARC file and then looking around for the proper text data. I'll just pull the text out of the HTML provided by the index rather than try to mess with all the text data.

**Comment by michaelharms** [comment]
Yes, I think you're right. I also use libraries like BeautifulSoup to extract the texts from the HTML. 

Thanks for closing the issue yourself again!
